"""Add cover image field to Concert model

Revision ID: 61ca9bf0ddd4
Revises: 7740c9631018
Create Date: 2024-10-09 23:17:44.986790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ca9bf0ddd4'
down_revision = '7740c9631018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
