"""Add Flight model

Revision ID: 6353d9f9aae3
Revises: b71a93c3e9dd
Create Date: 2024-10-19 00:06:36.416904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6353d9f9aae3'
down_revision = 'b71a93c3e9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('departure_airport', sa.String(length=3), nullable=False),
    sa.Column('arrival_airport', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('airline', sa.String(length=50), nullable=False),
    sa.Column('economy_price', sa.Float(), nullable=False),
    sa.Column('business_price', sa.Float(), nullable=False),
    sa.Column('available_economy_seats', sa.Integer(), nullable=False),
    sa.Column('available_business_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    # ### end Alembic commands ###
