"""Add available_tickets to Concert

Revision ID: 6fb9da01ce13
Revises: 61ca9bf0ddd4
Create Date: 2024-10-10 13:03:32.417557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb9da01ce13'
down_revision = '61ca9bf0ddd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_tickets', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.drop_column('available_tickets')

    # ### end Alembic commands ###
