"""Update concert ticket model

Revision ID: 7740c9631018
Revises: fe02c454ca23
Create Date: 2024-10-09 12:50:51.570381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7740c9631018'
down_revision = 'fe02c454ca23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_type', sa.Enum('VIP', 'REGULAR', name='tickettype'), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('RESERVED', 'PAID', 'CANCELED', name='ticketstatus'),
               existing_nullable=False)

    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_ticket_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('regular_ticket_price', sa.Float(), nullable=False))
        batch_op.drop_column('ticket_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_price', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('regular_ticket_price')
        batch_op.drop_column('vip_ticket_price')

    with op.batch_alter_table('concert_tickets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('RESERVED', 'PAID', 'CANCELED', name='ticketstatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('ticket_type')

    # ### end Alembic commands ###
